### ISSUE TITLE
Only inherit themes which are really needed

### ISSUE THREAD

**Issue by alexxcons** [PlagaMedicum/PlagueSur-icon-theme#8]
Hi PlaqueSur team,

now that the [related xdg merge request](https://gitlab.freedesktop.org/xdg/default-icon-theme/-/merge_requests/5) got merged and v0.18 of the spec got released, I am starting my mission to get the "Inherits" attribute right for popular icon-themes to prevent potentially missing icons 🙂

[Currently PlaqueSur has](https://github.com/PlagaMedicum/PlagueSur-icon-theme/blob/main/index.theme#L4):

> Inherits=WhiteSur-dark,breeze-dark,Adwaita,hicolor

I suppose it makes sense to list `WhiteSur-dark` if `PlaqueSur` uses some ofit's icons, though I wonder why `breeze-dark` and `Adwaita` are listed here ... are `PlaqueSur` and `WhiteSur-dark` lacking fd.org icons which need to be provided by these?

If there is no strong reason to keep them in the Inherits list, I would suggest dropping them.

If one/some of the other themes need to stay on the list for some reason, it makes sense to have a section in the README.md to explain packagers that the `plaquesur-icon-theme` package should have a hard dependency on the other listed themes.

**Comment by PlagaMedicum** [comment]
Hi! Thanks for your notice here. Those icon packs were added just in case generally. Even WhiteSur is not needed either, because PlagueSur is at a high level based on it. So maybe there is reason to leave hicolor only.

**Comment by alexxcons** [comment]
Only having hicolor sounds perfect :+1:  Thank you for taking care on PlaqueSur!

**Comment by PlagaMedicum** [comment]
Updated to hicolor only.
